name: where
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/Jaguar-dart/jaguar_orm
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.64.0 <2.0.0'

dependencies:
  jaguar_query:
  jaguar_orm:
  jaguar_query_postgres:

dev_dependencies:
  test: ^1.2.0
  build_runner:
  jaguar_orm_gen: ^2.1.1
